# This is a config for E2B sandbox template.
# You can use template ID (s7a2sq88wndzb67cq1gb) or template name (code-gen-nextjs-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("code-gen-nextjs-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("code-gen-nextjs-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('code-gen-nextjs-2')

team_id = "2e318b43-df18-4e40-bbcf-2d7d6cc983b5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "code-gen-nextjs-2"
template_id = "s7a2sq88wndzb67cq1gb"
